In [1]:
import exifread as ex
import folium as fol
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import mapclassify as mcl

In [2]:
with open('testimg.jpg', 'rb') as file_handle:
    tags = ex.process_file(file_handle)
df = pd.DataFrame([tags])
df

,Image Make,Image Model,Image Orientation,Image XResolution,Image YResolution,Image ResolutionUnit,Image Software,Image DateTime,Image HostComputer,Image YCbCrPositioning,...,MakerNote Tag 0x0046,MakerNote Tag 0x004A,MakerNote Tag 0x004D,MakerNote Tag 0x004E,MakerNote Tag 0x004F,MakerNote Tag 0x0052,MakerNote Tag 0x0053,MakerNote Tag 0x0055,MakerNote Tag 0x0058,JPEGThumbnail
0,Apple,iPhone 15,Horizontal (normal),72,72,Pixels/Inch,18.3.2,2025:07:18 15:41:02,iPhone 15,Centered,...,0,2,808505857/33752145,"[49, 81, 50, 16, 3, 162, 5, 10, 210, 6, 7, 8, ...","[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",0,1,0,2308,b'\xff\xd8\xff\xdb\x00\x84\x00\x01\x01\x01\x01...

In [3]:
file = gpd.read_file('states_provinces/states_provinces.shp')
file.head(5)

,featurecla,scalerank,adm1_code,diss_me,iso_3166_2,wikipedia,iso_a2,adm0_sr,name,name_alt,...,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,FCLASS_TLC,geometry
0,Admin-1 states provinces,3,ARG-1309,1309,AR-E,None,AR,1,Entre Ríos,Entre-Rios,...,None,None,None,None,None,None,None,None,None,"POLYGON ((-58.20011 -32.44713, -58.20012 -32.4..."
1,Admin-1 states provinces,6,URY-8,8,UY-PA,None,UY,1,Paysandú,None,...,None,None,None,None,None,None,None,None,None,"POLYGON ((-58.20012 -32.4472, -58.20011 -32.44..."
2,Admin-1 states provinces,2,IDN-1185,1185,ID-KI,None,ID,5,Kalimantan Timur,Kaltim,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((117.70361 4.16341, 117.70361 4..."
3,Admin-1 states provinces,6,MYS-1186,1186,MY-12,None,MY,5,Sabah,North Borneo,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((117.70361 4.16341, 117.70361 4..."
4,Admin-1 states provinces,3,CHL-2694,2694,CL-AP,None,CL,1,Arica y Parinacota,None,...,None,None,None,None,None,None,None,None,None,"POLYGON ((-69.51009 -17.50659, -69.50611 -17.5..."

In [ ]:
lat = file['']